name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Build
        run: |
          cp ./README.md ./regexpro/README.md
          cd ./regexpro
          npm i
          npm i -g typescript
          npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Bump Version and Publish
        run: |
          cd ./regexpro
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
